<!DOCTYPE html>
<#import "spring.ftl" as spring/>
<#setting classic_compatible=true>
<html>
<head>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&display=swap" rel="stylesheet">
    <title>Start</title>
    <link href="/css/startPage.css" rel="stylesheet"/>

</head>
<body>
<div class="welcome">
    WELCOME
    <ul class="choice">
        <li><a href="/signUp">Регистрация</a></li>
        <li><a href="/signIn">Вход</a></li>
    </ul>
</div>
</body>
</html>