<!DOCTYPE html>
<#import "spring.ftl" as spring/>
<#setting classic_compatible=true>
<html lang="en">
<head>
    <title>SignUp</title>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="/css/startPage.css" rel="stylesheet"/>
</head>
<body>
    <div class="welcome">
        СПАСИБО ЗА УЧАСТИЕ
    </div>
</body>
</html>